// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANbOiQCyZni1VNp9hwDJxCid6Fprgi9mY',
    appId: '1:88763634254:web:b7c1164ee17f1fce2ea91f',
    messagingSenderId: '88763634254',
    projectId: 'hogo-b849a',
    authDomain: 'hogo-b849a.firebaseapp.com',
    storageBucket: 'hogo-b849a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALpMfbRW3esq169_LG0jnLkOBk-D9mKGQ',
    appId: '1:88763634254:android:6faa742873966ab12ea91f',
    messagingSenderId: '88763634254',
    projectId: 'hogo-b849a',
    storageBucket: 'hogo-b849a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmuSzITb-oNdRpjcIbAJim_MAoZSBEQoM',
    appId: '1:88763634254:ios:eb081dd04af1bc4e2ea91f',
    messagingSenderId: '88763634254',
    projectId: 'hogo-b849a',
    storageBucket: 'hogo-b849a.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmuSzITb-oNdRpjcIbAJim_MAoZSBEQoM',
    appId: '1:88763634254:ios:eb081dd04af1bc4e2ea91f',
    messagingSenderId: '88763634254',
    projectId: 'hogo-b849a',
    storageBucket: 'hogo-b849a.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANbOiQCyZni1VNp9hwDJxCid6Fprgi9mY',
    appId: '1:88763634254:web:313eeea5d9021fc82ea91f',
    messagingSenderId: '88763634254',
    projectId: 'hogo-b849a',
    authDomain: 'hogo-b849a.firebaseapp.com',
    storageBucket: 'hogo-b849a.firebasestorage.app',
  );
}
